%% softCHeatEquation_MOLE_curvilinear_gridGenerator_CFL_heatmaps.m
% MOLE-style curvilinear heat equation on a grid generated by gridGenerator.
%
% Solves the forced heat equation:
%
%       u_t = alpha*Delta u + f(x,y,t)
%
% on a soft C / horseshoe physical domain.
%
% The physical grid is first generated by the single-grid reference-grid
% generator:
%
%       gridGenerator(grid_fun, Ns, Nt, Nsteps)
%
% The resulting generated grid X,Y is then passed into MOLE's curvilinear
% nodal operators:
%
%       [Nx, Ny] = nodal2DCurv(k, X, Y);
%       L = [Nx Ny]*[Nx; Ny];
%
% Manufactured exact solution:
%
%       u_exact(x,y,t)
%       =
%       exp(-t)*cos(pi*x/(2*rho*b1))*sin(pi*y/b1)
%
% Dirichlet boundary values are imposed from u_exact.
%
% The timestep is selected from a CFL-style condition based on the
% curvilinear diffusion operator.
%
% Plotting note:
%   The grid and reference grid are plotted physically.
%   The initial condition, numerical solution, exact solution, and error
%   are plotted as heatmaps in logical index space.

clc; clear; close all;

%% ------------------------------------------------------------------------
% Path setup
%
% Adjust these paths if your script lives somewhere else.

thisDir = fileparts(mfilename('fullpath'));
if isempty(thisDir)
    thisDir = pwd;
end

addpath(thisDir);
addpath(fullfile(thisDir, 'Grids'));

% MOLE path options. Keep whichever one matches your folder layout.
addpath(fullfile(thisDir, 'src', 'matlab_octave'));
addpath('../../src/matlab_octave');

rehash toolboxcache;

%% ------------------------------------------------------------------------
% Parameters

Ns = 41;          % grid points in xi direction
Nt = 41;          % grid points in eta direction

Nsteps = 10;      % gridGenerator reclustering iterations

k = 2;            % MOLE order of accuracy

alpha = 1.0;      % diffusion coefficient

method = "explicit";   % "implicit" or "explicit"

Tfinal = 1.0;
CFL = 0.2;
plotEvery = 25;

% Soft C parameters
rho = 2.0;
b0  = 1.0;
b1  = 2.0;

%% ------------------------------------------------------------------------
% Check required functions

if isempty(which('gridGenerator'))
    error(['Cannot find gridGenerator.m. Put it on the MATLAB path or in this folder.\n', ...
           'Diagnostic: run "which gridGenerator -all".']);
end

if isempty(which('nodal2DCurv'))
    error(['Cannot find nodal2DCurv.m. Make sure MOLE src/matlab_octave is on the path.\n', ...
           'Diagnostic: run "which nodal2DCurv -all".']);
end

fprintf('Using gridGenerator:\n  %s\n', which('gridGenerator'));
fprintf('Using nodal2DCurv:\n  %s\n\n', which('nodal2DCurv'));

%% ------------------------------------------------------------------------
% Generate grid using the single-grid grid generator
%
% grid_fun returns the initial boundary-fitted soft C grid. gridGenerator
% keeps the physical boundary fixed and optimizes the interior grid through
% the reference-grid spacing.

grid_fun = @(nx,ny) makeGridC_noPlot(nx, ny, rho, b0, b1);

[C_opt, E_grid, X, Y, Jc, pUopt, pVopt, Uref, Vref, gridInfo] = ...
    gridGenerator(grid_fun, Ns, Nt, Nsteps);

% Make sure output orientation is Nt x Ns.
if ~isequal(size(X), [Nt, Ns]) && isequal(size(X), [Ns, Nt])
    warning('gridGenerator returned X,Y as Ns x Nt. Transposing to Nt x Ns.');
    X = X.';
    Y = Y.';
end

if ~isequal(size(X), [Nt, Ns])
    error('Expected generated grid size Nt x Ns = %d x %d, got %s.', ...
        Nt, Ns, mat2str(size(X)));
end

fprintf('Generated grid complete:\n');
fprintf('  C_opt       = %.6e\n', C_opt);
fprintf('  Grid energy = %.6e\n', E_grid);
fprintf('  min(Jc)     = %.6e\n', min(Jc(:)));

if isfield(gridInfo, 'minq')
    fprintf('  minq        = %.6e\n', gridInfo.minq);
end
if isfield(gridInfo, 'ESJ')
    fprintf('  ESJ         = %.6e\n', gridInfo.ESJ);
end

%% ------------------------------------------------------------------------
% MOLE convention:
% X and Y are nodal coordinate arrays.

[n, m] = size(X);
Nnodes = n*m;

%% ------------------------------------------------------------------------
% Build MOLE curvilinear nodal Laplacian on generated grid

[Nx, Ny] = nodal2DCurv(k, X, Y);
L = [Nx Ny]*[Nx; Ny];

%% ------------------------------------------------------------------------
% Boundary indices for nodal Dirichlet data

bdry_idx = boundaryIdx2D(m, n);

%% ------------------------------------------------------------------------
% Choose timestep from CFL-style stability condition
%
% For the semi-discrete system
%
%       U_t = alpha*L*U + F,
%
% a practical explicit stability scale is based on the diagonal magnitude
% of alpha*L. For implicit time stepping, this CFL choice is not required
% for stability, but it keeps the time step physically reasonable and
% comparable across resolutions.
%
% Since L is sparse, force the diagonal data to full before using fprintf.

diagRateVec = full(abs(diag(L)));
diagRate = alpha * max(diagRateVec(:));

if diagRate <= 0 || ~isfinite(diagRate)
    error('Invalid CFL rate. Check the curvilinear operator L.');
end

dt = CFL / diagRate;
ntSteps = ceil(Tfinal / dt);
dt = Tfinal / ntSteps;

fprintf('\nMOLE curvilinear heat solve on generated soft C grid\n');
fprintf('  method     = %s\n', method);
fprintf('  nodes      = %d\n', Nnodes);
fprintf('  grid       = %d x %d\n', Ns, Nt);
fprintf('  max rate   = %.6e\n', diagRate);
fprintf('  CFL        = %.6e\n', CFL);
fprintf('  dt         = %.6e\n', dt);
fprintf('  time steps = %d\n', ntSteps);

%% ------------------------------------------------------------------------
% Initial condition from exact solution

t = 0.0;

Umat0 = uExact(X, Y, t, rho, b1);
Umat  = Umat0;

U = matToVec(Umat);

% Strongly enforce boundary values at t = 0.
BCmat = uExact(X, Y, t, rho, b1);
BCvec = matToVec(BCmat);
U(bdry_idx) = BCvec(bdry_idx);

%% ------------------------------------------------------------------------
% Build time-stepping matrix

Iop = speye(Nnodes);

switch method
    case "implicit"

        % Backward Euler:
        %
        %   (I - dt*alpha*L) U^{n+1}
        %   =
        %   U^n + dt*f^{n+1}

        A = Iop - dt*alpha*L;

        % Strong Dirichlet boundary enforcement.
        A(bdry_idx,:) = 0;
        for q = 1:numel(bdry_idx)
            A(bdry_idx(q), bdry_idx(q)) = 1;
        end

    case "explicit"

        % Forward Euler:
        %
        %   U^{n+1}
        %   =
        %   U^n + dt*(alpha*L*U^n + f^n)

        A = Iop + dt*alpha*L;

    otherwise
        error('method must be "implicit" or "explicit".');
end

%% ------------------------------------------------------------------------
% Time integration

for step = 1:ntSteps

    switch method

        case "implicit"

            tnew = t + dt;

            Fmat = sourceTerm(X, Y, tnew, rho, b1, alpha);
            rhs = U + dt*matToVec(Fmat);

            % Dirichlet boundary values at the new time.
            BCmat = uExact(X, Y, tnew, rho, b1);
            BCvec = matToVec(BCmat);
            rhs(bdry_idx) = BCvec(bdry_idx);

            U = A\rhs;

            t = tnew;

        case "explicit"

            Fmat = sourceTerm(X, Y, t, rho, b1, alpha);
            rhs = matToVec(Fmat);

            U = A*U + dt*rhs;

            t = t + dt;

            % Strongly reset boundary values.
            BCmat = uExact(X, Y, t, rho, b1);
            BCvec = matToVec(BCmat);
            U(bdry_idx) = BCvec(bdry_idx);
    end

    if mod(step,plotEvery) == 0 || step == ntSteps
        fprintf('  step %5d / %5d, t = %.5f\n', step, ntSteps, t);
    end

end

Umat = vecToMat(U, n, m);

%% ------------------------------------------------------------------------
% Exact solution and error at final time

Uexact = uExact(X, Y, Tfinal, rho, b1);

Err = Umat - Uexact;

% Nodal error norms.
L2err = sqrt(mean(Err(:).^2));
Linferr = max(abs(Err(:)));

fprintf('\nERROR at T = %.5f:\n', Tfinal);
fprintf('  L2 nodal   = %.6e\n', L2err);
fprintf('  Linf nodal = %.6e\n', Linferr);

%% ------------------------------------------------------------------------
% Shared color limits for non-error solution plots

solutionValues = [Umat0(:); Umat(:); Uexact(:)];
solCLim = [min(solutionValues), max(solutionValues)];

if abs(solCLim(2) - solCLim(1)) < 1e-14
    solCLim = solCLim + [-1, 1]*1e-14;
end

%% ------------------------------------------------------------------------
% Plot generated grid in physical space

figure('Color','w'); hold on; axis equal; box on;
for j = 1:Nt
    plot(X(j,:), Y(j,:), 'k-', 'LineWidth', 0.5);
end
for i = 1:Ns
    plot(X(:,i), Y(:,i), 'k-', 'LineWidth', 0.5);
end
title('Generated soft C / horseshoe grid');
xlabel('x'); ylabel('y');

%% ------------------------------------------------------------------------
% Plot reference grid from gridGenerator

if exist('Uref','var') && ~isempty(Uref)
    figure('Color','w'); hold on; axis equal; box on;
    for j = 1:size(Uref,1)
        plot(Uref(j,:), Vref(j,:), 'b-', 'LineWidth', 0.5);
    end
    for i = 1:size(Uref,2)
        plot(Uref(:,i), Vref(:,i), 'b-', 'LineWidth', 0.5);
    end
    title('Reference grid from gridGenerator');
    xlabel('u'); ylabel('v');
end

%% ------------------------------------------------------------------------
% Plot initial condition as physical heatmap

figure('Color','w');
pcolor(X, Y, Umat0);
shading interp;
axis equal tight;
box on;
cb = colorbar;
clim(solCLim);
ylabel(cb, 'temperature');
title('Initial condition from manufactured exact solution');
xlabel('x'); ylabel('y');

%% ------------------------------------------------------------------------
% Plot numerical solution as physical heatmap

figure('Color','w');
pcolor(X, Y, Umat);
shading interp;
axis equal tight;
box on;
cb = colorbar;
clim(solCLim);
ylabel(cb, 'temperature');
title(sprintf('MOLE curvilinear numerical solution on generated grid, t = %.3f', Tfinal));
xlabel('x'); ylabel('y');

%% ------------------------------------------------------------------------
% Plot exact solution as physical heatmap

figure('Color','w');
pcolor(X, Y, Uexact);
shading interp;
axis equal tight;
box on;
cb = colorbar;
clim(solCLim);
ylabel(cb, 'temperature');
title(sprintf('Exact manufactured solution, t = %.3f', Tfinal));
xlabel('x'); ylabel('y');

%% ------------------------------------------------------------------------
% Plot error as physical heatmap

figure('Color','w');
pcolor(X, Y, Err);
shading interp;
axis equal tight;
box on;
cb = colorbar;
ylabel(cb, 'error');
title(sprintf('Error, L2 = %.3e, Linf = %.3e', L2err, Linferr));
xlabel('x'); ylabel('y');
function [X, Y] = makeGridC_noPlot(nptsx, nptsy, rho, b0, b1)

Ni = nptsx;
Nj = nptsy;

xi  = linspace(0,1,Ni+1);
eta = linspace(0,1,Nj+1);

[Xi, Eta] = meshgrid(xi, eta); %#ok<ASGLU>

R = b0 + (b1 - b0) * Eta;
Theta = pi * (1 - 2*Xi)/2;

X = rho * R .* cos(Theta);
Y = R .* sin(Theta);

end

%% =======================================================================
function u = uExact(x, y, t, rho, b1)

a = pi/(2*rho*b1);
b = pi/b1;

u = exp(-t) .* cos(a*x) .* sin(b*y);

end

%% =======================================================================
function f = sourceTerm(x, y, t, rho, b1, alpha)
% Manufactured source term for:
%
%       u_t = alpha*Delta u + f
%
% Exact solution:
%
%       u = exp(-t)*cos(a*x)*sin(b*y)
%
% Then:
%
%       u_t     = -u
%       Delta u = -(a^2+b^2)u
%
% Therefore:
%
%       f = u_t - alpha*Delta u
%         = (alpha*(a^2+b^2) - 1)u

a = pi/(2*rho*b1);
b = pi/b1;

u = uExact(x, y, t, rho, b1);

f = (alpha*(a^2 + b^2) - 1) .* u;

end

%% =======================================================================
function v = matToVec(Umat)
% Matrix-to-vector conversion.
%
% This convention matches the indexing used by boundaryIdx2D:
%
%       k = (j-1)*m + i
%
% where j is the row index and i is the column index.

v = reshape(Umat.', [], 1);

end

%% =======================================================================
function Umat = vecToMat(v, n, m)
% Inverse of matToVec.

Umat = reshape(v, m, n).';

end

%% =======================================================================
function idx = boundaryIdx2D(m, n)
% boundaryIdx2D
% Returns boundary-node indices for a matrix of size n-by-m, using the
% vectorization convention reshape(Umat.', [], 1).
%
% Matrix index:
%
%       row j = 1,...,n
%       col i = 1,...,m
%
% Vector index:
%
%       k = (j-1)*m + i

idx = [];

% Bottom and top rows
for i = 1:m
    idx(end+1,1) = sub2vec(1, i, m); %#ok<AGROW>
    idx(end+1,1) = sub2vec(n, i, m); %#ok<AGROW>
end

% Left and right columns, excluding corners already included
for j = 2:n-1
    idx(end+1,1) = sub2vec(j, 1, m); %#ok<AGROW>
    idx(end+1,1) = sub2vec(j, m, m); %#ok<AGROW>
end

idx = unique(idx);

end

%% =======================================================================
function k = sub2vec(j, i, m)
% Matrix index (j,i) to vector index under reshape(Umat.', [], 1).

k = (j-1)*m + i;

end