%% softCHeatEquation_analytic_reference_shared_colorbars.m
% Conservative mimetic-style finite-volume heat equation on the soft C grid.
%
% Solves the forced heat equation:
%
%       u_t = Delta u + f(x,y,t)
%
% on the soft C-shaped physical domain generated by makeGridC_noPlot.
%
% Manufactured exact solution:
%
%       u_exact(x,y,t)
%       =
%       exp(-t)*cos(pi*x/(2*rho*b1))*sin(pi*y/b1)
%
% The source term f is chosen so that u_exact satisfies the PDE.
%
% Dirichlet boundary values are imposed from u_exact.
%
% The spatial operator is a conservative face-flux operator:
%
%       div(grad u)
%       approx
%       (1/area_K) sum_faces T_f (u_neighbor - u_K)
%
% with boundary fluxes using exact Dirichlet data.
%
% Plotting note:
%   The initial condition, numerical solution, and exact solution use the
%   same colorbar limits. The error plot uses its own colorbar scale.

clc; clear; close all;

%% --- Parameters ---
Ns = 41;          % grid points in xi direction
Nt = 41;          % grid points in eta direction

Tfinal = 1;
CFL = 0.2;
plotEvery = 25;

% Soft C parameters
rho = 2.0;
b0  = 1.0;
b1  = 2.0;

%% --- Build soft C grid ---
[X, Y] = makeGridC_noPlot(Ns-1, Nt-1, rho, b0, b1);

%% --- Geometry for cell-centered finite-volume solve ---
geom = buildCellGeometry(X, Y);
Nc = geom.Nc;

%% --- Initial condition from exact solution ---
t = 0.0;
u0 = uExact(geom.xc, geom.yc, t, rho, b1);
u = u0;

%% --- Stable explicit time step ---
% The forward Euler stability condition is based on the diagonal diffusion
% rate of the conservative face-flux operator:
%
%       dt = CFL / max_K sum_{f in dK} T_f / area_K
%
% This replaces the Cartesian estimate dt ~ C dx^2.

diagRate = zeros(Nc,1);

for k = 1:numel(geom.faces)
    f = geom.faces(k);

    if f.right > 0
        diagRate(f.left)  = diagRate(f.left)  + f.T / geom.area(f.left);
        diagRate(f.right) = diagRate(f.right) + f.T / geom.area(f.right);
    else
        diagRate(f.left) = diagRate(f.left) + f.T / geom.area(f.left);
    end
end

dt = CFL / max(diagRate);
ntSteps = ceil(Tfinal / dt);
dt = Tfinal / ntSteps;

fprintf('Soft C mimetic finite-volume heat solve\n');
fprintf('  cells      = %d\n', Nc);
fprintf('  max rate   = %.6e\n', max(diagRate));
fprintf('  dt         = %.6e\n', dt);
fprintf('  time steps = %d\n', ntSteps);

%% --- Time integration: forward Euler conservative flux form ---
for n = 1:ntSteps

    rhs = heatRHS_mimetic(u, t, geom, rho, b1);

    u = u + dt * rhs;
    t = t + dt;

    if mod(n,plotEvery) == 0 || n == ntSteps
        fprintf('  step %4d / %4d, t = %.5f\n', n, ntSteps, t);
    end

end

%% --- Exact solution and error at final time ---
ue = uExact(geom.xc, geom.yc, Tfinal, rho, b1);

err = u - ue;

L2err = sqrt(sum(geom.area .* err.^2) / sum(geom.area));
Linferr = max(abs(err));

fprintf('\nERROR at T = %.5f:\n', Tfinal);
fprintf('  L2    = %.6e\n', L2err);
fprintf('  Linf  = %.6e\n', Linferr);

%% --- Shared color limits for non-error solution plots ---
% These limits are used for:
%   1. Initial condition
%   2. Numerical solution
%   3. Exact solution
%
% The error plot uses its own color scale.

solutionValues = [u0(:); u(:); ue(:)];
solCLim = [min(solutionValues), max(solutionValues)];

% Avoid a degenerate color range if the solution is constant.
if abs(solCLim(2) - solCLim(1)) < 1e-14
    solCLim = solCLim + [-1, 1]*1e-14;
end

%% --- Plot grid ---
figure('Color','w'); hold on; axis equal; box on;
for j = 1:Nt
    plot(X(j,:), Y(j,:), 'k-', 'LineWidth', 0.5);
end
for i = 1:Ns
    plot(X(:,i), Y(:,i), 'k-', 'LineWidth', 0.5);
end
title('Soft C / horseshoe grid');
xlabel('x'); ylabel('y');

%% --- Plot initial condition ---
figure('Color','w'); hold on; axis equal; box on;
plotCellField(X, Y, u0, Ns, Nt);
cb = colorbar;
clim(solCLim);
ylabel(cb, 'temperature');
title('Initial condition from manufactured exact solution');
xlabel('x'); ylabel('y');

%% --- Plot numerical solution ---
figure('Color','w'); hold on; axis equal; box on;
plotCellField(X, Y, u, Ns, Nt);
cb = colorbar;
clim(solCLim);
ylabel(cb, 'temperature');
title(sprintf('Numerical solution, t = %.3f', Tfinal));
xlabel('x'); ylabel('y');

%% --- Plot exact solution ---
figure('Color','w'); hold on; axis equal; box on;
plotCellField(X, Y, ue, Ns, Nt);
cb = colorbar;
clim(solCLim);
ylabel(cb, 'temperature');
title(sprintf('Exact manufactured solution, t = %.3f', Tfinal));
xlabel('x'); ylabel('y');

%% --- Plot error ---
figure('Color','w'); hold on; axis equal; box on;
plotCellField(X, Y, err, Ns, Nt);
cb = colorbar;
ylabel(cb, 'error');
title(sprintf('Error, L2 = %.3e, Linf = %.3e', L2err, Linferr));
xlabel('x'); ylabel('y');

%% =======================================================================
function [X, Y] = makeGridC_noPlot(nptsx, nptsy, rho, b0, b1)

Ni = nptsx;
Nj = nptsy;

xi  = linspace(0,1,Ni+1);
eta = linspace(0,1,Nj+1);

[Xi, Eta] = meshgrid(xi, eta);

R = b0 + (b1 - b0) * Eta;
Theta = pi * (1 - 2*Xi)/2;

X = rho * R .* cos(Theta);
Y = R .* sin(Theta);

end

%% =======================================================================
function geom = buildCellGeometry(X, Y)
% Build cell centers, areas, and face transmissibilities.
%
% Cell index:
%
%       id(j,i), j = 1,...,ny, i = 1,...,nx

[J,I] = size(X);

ny = J - 1;
nx = I - 1;
Nc = nx * ny;

id = @(j,i) (j-1)*nx + i;

xc = zeros(Nc,1);
yc = zeros(Nc,1);
area = zeros(Nc,1);

for j = 1:ny
    for i = 1:nx

        k = id(j,i);

        px = [X(j,i), X(j,i+1), X(j+1,i+1), X(j+1,i)];
        py = [Y(j,i), Y(j,i+1), Y(j+1,i+1), Y(j+1,i)];

        xc(k) = mean(px);
        yc(k) = mean(py);
        area(k) = abs(polyarea(px,py));

    end
end

faces = struct('left',{},'right',{},'T',{},'xb',{},'yb',{});

%% Vertical-ish faces
for j = 1:ny
    for iFace = 1:I

        xa = X(j,iFace);     ya = Y(j,iFace);
        xb = X(j+1,iFace);   yb = Y(j+1,iFace);

        faceLength = hypot(xb-xa, yb-ya);
        xm = 0.5*(xa+xb);
        ym = 0.5*(ya+yb);

        if iFace == 1
            kL = id(j,1);
            kR = 0;
            dist = hypot(xc(kL)-xm, yc(kL)-ym);

        elseif iFace == I
            kL = id(j,nx);
            kR = 0;
            dist = hypot(xc(kL)-xm, yc(kL)-ym);

        else
            kL = id(j,iFace-1);
            kR = id(j,iFace);
            dist = hypot(xc(kR)-xc(kL), yc(kR)-yc(kL));
        end

        T = faceLength / max(dist,1e-14);

        faces(end+1) = struct( ...
            'left',  kL, ...
            'right', kR, ...
            'T',     T, ...
            'xb',    xm, ...
            'yb',    ym); %#ok<AGROW>

    end
end

%% Horizontal-ish faces
for jFace = 1:J
    for i = 1:nx

        xa = X(jFace,i);     ya = Y(jFace,i);
        xb = X(jFace,i+1);   yb = Y(jFace,i+1);

        faceLength = hypot(xb-xa, yb-ya);
        xm = 0.5*(xa+xb);
        ym = 0.5*(ya+yb);

        if jFace == 1
            kL = id(1,i);
            kR = 0;
            dist = hypot(xc(kL)-xm, yc(kL)-ym);

        elseif jFace == J
            kL = id(ny,i);
            kR = 0;
            dist = hypot(xc(kL)-xm, yc(kL)-ym);

        else
            kL = id(jFace-1,i);
            kR = id(jFace,i);
            dist = hypot(xc(kR)-xc(kL), yc(kR)-yc(kL));
        end

        T = faceLength / max(dist,1e-14);

        faces(end+1) = struct( ...
            'left',  kL, ...
            'right', kR, ...
            'T',     T, ...
            'xb',    xm, ...
            'yb',    ym); %#ok<AGROW>

    end
end

geom = struct();
geom.Nc = Nc;
geom.nx = nx;
geom.ny = ny;
geom.xc = xc;
geom.yc = yc;
geom.area = area;
geom.faces = faces;

end

%% =======================================================================
function rhs = heatRHS_mimetic(u, t, geom, rho, b1)
% Conservative mimetic-style heat operator plus manufactured source.

rhs = sourceTerm(geom.xc, geom.yc, t, rho, b1);

for k = 1:numel(geom.faces)

    f = geom.faces(k);

    L = f.left;
    R = f.right;

    if R > 0

        % Interior face flux.
        % Equal and opposite contributions enforce local conservation.
        fluxLR = f.T * (u(R) - u(L));

        rhs(L) = rhs(L) + fluxLR / geom.area(L);
        rhs(R) = rhs(R) - fluxLR / geom.area(R);

    else

        % Boundary face with exact Dirichlet value.
        ub = uExact(f.xb, f.yb, t, rho, b1);

        fluxLB = f.T * (ub - u(L));

        rhs(L) = rhs(L) + fluxLB / geom.area(L);

    end

end

end

%% =======================================================================
function u = uExact(x, y, t, rho, b1)

a = pi/(2*rho*b1);
b = pi/b1;

u = exp(-t) .* cos(a*x) .* sin(b*y);

end

%% =======================================================================
function f = sourceTerm(x, y, t, rho, b1)
% Manufactured source term for:
%
%       u_t = Delta u + f
%
% Exact solution:
%
%       u = exp(-t)*cos(a*x)*sin(b*y)
%
% Then:
%
%       u_t     = -u
%       Delta u = -(a^2+b^2)u
%
% Therefore:
%
%       f = u_t - Delta u = (a^2+b^2-1)u

a = pi/(2*rho*b1);
b = pi/b1;

u = uExact(x, y, t, rho, b1);

f = (a^2 + b^2 - 1) .* u;

end

%% =======================================================================
function plotCellField(X, Y, q, Ns, Nt)
% q is a cell-centered vector ordered by:
%
%       k = (j-1)*(Ns-1) + i

nx = Ns - 1;

for j = 1:Nt-1
    for i = 1:Ns-1

        k = (j-1)*nx + i;

        px = [X(j,i), X(j,i+1), X(j+1,i+1), X(j+1,i)];
        py = [Y(j,i), Y(j,i+1), Y(j+1,i+1), Y(j+1,i)];

        patch(px, py, q(k), 'EdgeColor', 'none');

    end
end

axis equal tight;

end